dist: trusty
sudo: false

language: node_js
node_js: "stable"

node_js:
  - node

services:
  - postgresql

before_script:
  - psql -c 'create database doc-mgt-system-test;' -U postgres
  - NODE_ENV=travis npm run db:migrate

