dist: trusty
sudo: required

language: node_js
node_js: "stable"

node_js:
  - node

addons:
  postgresql: "9.5"

services:
  - postgresql

# before_script:
#   - psql -c 'create database dms_test;' -U postgres
#   - npm install
script:
  - psql -c 'create database dms_test;' -U postgres
  - npm test

after_success:
- npm run coveralls
