dist: trusty
sudo: false

language: node_js
node_js: "stable"

services:
  - postgresql

before_script:
    - createdb dms-test
    - npm install

script:
  - npm test

after_success:
  - cat coverage/*lcov.info | ./node_modules/.bin/coveralls 

addons:
  postgresql: "9.3"
