dist: trusty
sudo: false

language: node_js
node_js: "stable"

node_js:
  - node

services:
  - postgresql

before_script:
  - psql -c 'create database dms_test;' -U postgres
  - NODE_ENV=travis npm run migrate-test

