dist: trusty
sudo: required

language: node_js
node_js: "stable"

node_js:
  - node

services:
  - postgresql

before_script:
  - npm install
  - psql -c 'create database dms_test;' -U postgres
script:
  - npm test

after_success:
- npm run coveralls
