language: node_js
node_js: "stable"

node_js:
  - node

services:
  - postgresql

before_install:
  - psql -c 'create database dms_test;' -U postgres
  - NODE_ENV=production npm run migrate-test


after_success:
  - node node_modules/codeclimate-test-reporter/bin/codeclimate < coverage/lcov.info

